version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.0.2
    steps:
      - checkout

      - run:
          name: Ruby version
          command: ruby --version

      - run:
          name: Install Bundler 2
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo rm /usr/local/bin/bundler
            sudo gem install bundler

      - run:
          name: Bundler version
          command: bundle --version

      - restore_cache:
          keys:
            - ruby-deps-v1-{{ checksum "show-gem-junk.gemspec" }}
            - ruby-deps-v1-

      - run:
          name: Install Ruby dependencies
          command: bundle check || bundle install

      - save_cache:
          key: ruby-deps-v1-{{ checksum "show-gem-junk.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          name: Run tests
          command: bin/rake test

      - run:
          name: Lint code
          command: bin/rubocop

      - run:
          name: Build gem
          command: bin/rake build

      - run:
          name: Inspect gem contents
          command: |
            cd pkg
            tar xf *.gem
            tar tvf data.tar.gz
